apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}-role-binding
  labels:
{{ include "app.labels.common" $ | indent 4 }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Release.Name }}-{{ .Values.app.name }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-{{ .Values.app.name }}
