name: Build Release
on:
  push:
    tags:
      - '**'
jobs:
  helm:
    uses: onecx/ci-common/.github/workflows/helm-release.yml@v1
    secrets: inherit
    with:
      templateValuesYaml: ''
      templateReleaseValuesYaml: ''
  changelog:
    uses: onecx/ci-common/.github/workflows/generate-changelog.yml@v1
    needs: helm
    secrets: inherit